name: Zaki Direct Deploy
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'رقم المختبر'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Install and Authenticate'
        run: |
          # 1. تفعيل المفتاح السحري بأسلوب مباشر
          gcloud auth activate-refresh-token ${{ secrets.GCP_TOKEN }} --client-id="407408718192.apps.googleusercontent.com" --client-secret="d9Q0vAL2A6pSp6qE8sPSBv9p"
          
          # 2. ضبط المشروع المتغير
          gcloud config set project ${{ github.event.inputs.project_id }}
          
          # 3. النشر المباشر
          gcloud run deploy zaki-server \
            --source . \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080 --quiet
          
          echo "✅ الرابط النهائي هو:"
          gcloud run services describe zaki-server --region europe-west1 --format='value(status.url)'
