name: Zaki Final Boss
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TK: 1//04iwQ7-zxAN9vCgYIARAAGAQSNwF-L9Ir7BMQ8p1hrb2pU8dn_pdnienoZ_8qPEpfQfVCyNW0vNvoiNfH0aLRPQJUfzF6dZWTQko
      ID: 407408718192.apps.googleusercontent.com
      SR: d9Q0vAL2A6pSp6qE8sPSBv9p
    steps:
      - uses: actions/checkout@v3
      - name: 'Direct Power Deploy'
        run: |
          # الأوامر الآن قصيرة جدا ومستحيل تنقسم
          gcloud auth activate-refresh-token $TK --client-id=$ID --client-secret=$SR
          
          gcloud run deploy zaki-server --source . --project=${{ github.event.inputs.project_id }} --region=europe-west1 --allow-unauthenticated --port=8080 --quiet
